<?php

return [
    App\Providers\ApiEndpointServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\ConfigVersionServiceProvider::class,
    App\Providers\DebuggingServiceProvider::class,
    App\Providers\EntityServiceProvider::class,
    App\Providers\FieldTypeServiceProvider::class,
    App\Providers\MarketplaceServiceProvider::class,
    App\Providers\MenuServiceProvider::class,
    App\Providers\ModuleServiceProvider::class,
    App\Providers\PermissionServiceProvider::class,
    App\Providers\PlatformExtensionsServiceProvider::class,
    App\Providers\PlatformServicesProvider::class,
    App\Providers\PluginSDKServiceProvider::class,
    App\Providers\PluginSecurityServiceProvider::class,
    App\Providers\PluginServiceProvider::class,
    App\Providers\RepositoryServiceProvider::class,
    App\Providers\SchedulerServiceProvider::class,
    App\Providers\ShortcodeServiceProvider::class,
    App\Providers\TelescopeServiceProvider::class,
    App\Providers\TranslationServiceProvider::class,
    App\Providers\ViewServiceProvider::class,
];
